### ISSUE TITLE
Обратная связь

### ISSUE THREAD

**Issue by SmilePunk420** [artemyakovlev94/simple_admin_epf#1]
Добрый день. Напишите, пожалуйста, на почту chepyashev@intertech.pro, по поводу интеграции Фронтол и Далион, почему-то исчез репозиторий у Вас.

**Comment by artemyakovlev94** [comment]
Данная интеграция не связана с проектом Simple

**Comment by SmilePunk420** [comment]
Артём, здравствуйте, я знаю, но Ваших контактов не было указано и я решил так получить от Вас обратную связь. Я на прошлой неделе нашёл у Вас проект по продаже в рассрочку, а вчера столкнулся с тем, что он уже недоступен. Мне необходимо реализовать проект по продаже в долг в Фронтол 6, хотел посмотреть на Ваше решение. Есть возможность получить доступ? 

--------------------------------------------------------------------------- 
С уважением, 
Данияр Чепяшев 

Рабочий телефон: 8-(391)-989-99-22 (доб. 934) 
Мобильный телефон: 8-950-960-1240 


От: "Artem" ***@***.***> 
Кому: "artemyakovlev94/simple_admin_epf" ***@***.***> 
Копия: "chepyashev" ***@***.***>, "Author" ***@***.***> 
Отправленные: Понедельник, 30 Сентябрь 2024 г 22:48:24 
Тема: Re: [artemyakovlev94/simple_admin_epf]Обратная связь(Issue #1) 





Данная интеграция не связана с проектом Simple

**Comment by artemyakovlev94** [comment]
> Есть возможность получить доступ?

Добрый день! Открыл доступ. Сделайте форк чтобы при смене режима видно было что кто-то работает с репозиторием.
